# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 744e9fd108bf6a94fa0461d3fae52c4b1d909dc783ceeef210ed693b9ef1f1fc2ce59249d428c792dd8115dae99e6154e48a8c949174188b90c7e95d99a2abc6

test:
  secret_key_base: 7cec322347fb32209ad89461f9edb16ed38aa39eaa01acfc3c663a6af531587f764202af4b84dc59346d12bab71e7cc864ef695698bbcc8490b87ee68c13fb86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
